### PR TITLE
Create allianceOfGenomeResources

### PR DESCRIPTION
**Pull request by kyook**
{
	"@context": "http://schema.org",
	"@type": "DataCatalog",
	"name": "Alliance of Genome Resources",
	"description": "The unified Alliance information system represents the union, rather than intersection, of data and information represented in the current individual Model Organism Databases, WormBase, Flybase, Saccharomyces Genome Database, Zebrafish Information Network, Mouse Genome Informatics, Rat Genome Database, and the Gene Ontology Consortium. These Alliance pages provide the best of each MOD in one place while maintaining community integrity and preserving the unique aspects of each model organism.  Through the implementation of a shared, modular information system architecture, the Alliance seeks to serve diverse user communities including (i) human geneticists who want access to all model organism data for orthologous human genes; (ii) basic science researchers who use specific model organisms to understand fundamental biology; (iii) computational biologists and data scientists who need access to standardized, well-structured data, both big and small; and (iv) educators and students.",
	"url": "https://www.alliancegenome.org",
	"keywords": [
		"Model organism database",
		"Model organism",
		"Genome resources",
		"Biomedical research",
		"Caenorhabditis",
		"Drosophila",
		"Danio",
		"Homo sapien",
		"Mus",
		"Mouse",
		"Fruit fly",
		"free living nematode",
		"Rattus",
		"Norwegian rat",
		"Gene ontology",
		"Saccharomyces"
	],
	"dateModified": "2018.11.03",
	"sourceOrganization": [{
			"@type": "Organization",
			"name": "WormBase",
			"url": "https://www.wormbase.org"
		},
		{
			"@type": "Organization",
			"name": "FlyBase",
			"url": "https://www.flybase.org"
		},
		{
			"@type": "Organization",
			"name": "Zebrafish Information Network",
			"alternateName": "ZFIN",
			"url": "https://www.zfin.org"
		},
		{
			"@type": "Organization",
			"name": "Rat Genome Database",
			"alternateName": "RGD",
			"url": "https://rgd.mcw.edu/"
		},
		{
			"@type": "Organization",
			"name": "Mouse Genome Informatics",
			"alternateName": "MGI",
			"url": "http://www.informatics.jax.org/"
		},
     	{
			"@type": "Organization",
			"name": "Gene Ontology Consortium",
			"alternateName": "GO",
			"url": "http://www.geneontology.org/"
		}, 
        {
                        "@type": "Organization",
                        "name": "Saccharomyces Genome Database",
                        "alternateName": "SGD",
                        "url": "http://www.yeastgenome.org/"
                 },
	],
	"license": {
		"@type": "CreativeWork",
		"name": "Creative Commons CC BY3.0 Attribution",
		"url": "https://creativecommons.org/licenses/by/3.0/"
	}
}

### CODE REVIEW

**Comment by srengel** [comment]
please add:

{
"@type": "Organization",
"name": "Saccharomyces Genome Database",
"alternateName": "SGD",
"url": "http://www.yeastgenome.org/"
},

**Comment by kyook** [comment]
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "DataCatalog",
  "name": "Alliance of Genome Resources",
  "description": "The unified Alliance information system represents the union, rather than intersection, of data and information represented in the current individual Model Organism Databases, WormBase, Flybase, Saccharomyces Genome Database, Zebrafish Information Network, Mouse Genome Informatics, Rat Genome Database, and the Gene Ontology Consortium. These Alliance pages provide the best of each MOD in one place while maintaining community integrity and preserving the unique aspects of each model organism.  Through the implementation of a shared, modular information system architecture, the Alliance seeks to serve diverse user communities including (i) human geneticists who want access to all model organism data for orthologous human genes; (ii) basic science researchers who use specific model organisms to understand fundamental biology; (iii) computational biologists and data scientists who need access to standardized, well-structured data, both big and small; and (iv) educators and students.",
  "url": "https://www.alliancegenome.org",
  "identifier": "www.identifiers.org/agr", 
  "dataset": [
        {
            "@type": "Dataset",
            "name": "Alliance of Genome Resources",
            "description": "A collaborative output of curated data from 6 Model Organism Databases and the Gene Ontology",
            "identifier": "https://identifiers.org/agr",
            "url": "http://www.alliancegenome.org/",
  "keywords": [
    "Model organism database",
    "Model organism",
    "Genome resource",
    "Biomedical research",
    "Caenorhabditis",
    "Drosophila",
    "Danio",
    "Homo sapien",
    "Mus",
    "Laboratory mouse",
    "Fruit fly",
    "free living nematode",
    "Rattus",
    "Norwegian rat",
    "Laboratory rat",
    "Gene ontology",
    "Saccharomyces", 
    "yeast",
    "Disease", 
    "Phenotype",
    "Gene",
    "Curated database"
  ],
            "version": "2.1",
            "license": {
                "@type": "CreativeWork",
                "name": "Creative Commons Attribution-ShareAlike 3.0 Unported",
                "url": "https://creativecommons.org/licenses/by-sa/3.0/"
            },
            "distribution": {
                "@type": "DataDownload",
                "contentUrl": "http://www.guidetopharmacology.org/DATA/public_iuphardb_v2017.5.zip",
                "fileFormat": "application/zip of a SQL file"
            }
            }
  ],
  "sourceOrganization": [
{
    "@type": "Organization",
    "name": "WormBase",
    "url": "https://www.wormbase.org"
    },
{
    "@type": "Organization",
    "name": "FlyBase",
    "url": "https://www.flybase.org"
  },
{
    "@type": "Organization",
    "name": "Zebrafish Information Network",
    "alternateName": "ZFIN",
    "url": "https://www.zfin.org"
  },
{
    "@type": "Organization",
    "name": "Rat Genome Database",
	"alternateName": "RGD",
	"url": "https://rgd.mcw.edu"
  },
{
    "@type": "Organization",
    "name": "Mouse Genome Informatics",
	"alternateName": "MGI",
	"url": "http://www.informatics.jax.org"
  },
{
    "@type": "Organization",
    "name": "Saccharomyces Genome Database",
	"alternateName": "SGD",
	"url": "https://www.yeastgenome.org"
  },  
{
    "@type": "Organization",
    "name": "Gene Ontology Consortium",
	"alternateName": "GO",
	"url": "https://www.geneontology.org"
    }
  ]
  }
</script>

**Comment by srengel** [comment]
please add 'yeast' to the keyword array.  thanks.

**Comment by kyook** [comment]
> please add 'yeast' to the keyword array. thanks.

added

**Comment by AlasdairGray** [comment]
It looks like the example file is empty to me. Is the example just in the comments here or is it in the file as well?

**Comment by AlasdairGray** [comment]
Resolved in #245

**Pull request closed without merging**
