### PR TITLE
tool profile example

### PR DESCRIPTION
**Pull request by albangaignard**
Added an example for Bioschemas markup generated by bio.tools.

### CODE REVIEW

**Review by ljgarcia — CHANGES_REQUESTED** [review]
We want to encourage the use of dct:conformsTo, which is missing here.
I would also suggest removing those namespaces from the context that are not used.

I am familiar with this serialization of JSON-LD but I do not know if we prefer a simpler one for Bioscheams examples. @AlasdairGray any thoughts?

**Comment by AlasdairGray** [comment]
I agree that `dct:conformsTo` must be present.

I would also suggest that we replace `biotools:primaryContact` with `schema:maintainer`.

We now also have two methods for capturing inputs and outputs. The `ComputationalWorkflow` working group have proposed that we add properties for `input` and `output`. I guess for now we can leave these as `edam:input` and `edam:output` but we really should have a single method.

**Comment by alaninmcr** [comment]
Is it worth doing this as the ComputationalTool release is in progress?

**Comment by albangaignard** [comment]
Thanks for your feedbacks, completely agree. This example comes from the current implementation of Bioschemas in bio.tools, not yet compliant with 1.0-release. I will manually modify this example, that conforms to the last draft version.

**Comment by AlasdairGray** [comment]
> Is it worth doing this as the ComputationalTool release is in progress?

The profile needs to go out for community comment, and this would be something that I would provide as a comment, so yes it is worth getting fixed.

**Comment by ljgarcia** [comment]
> 
> 
> > Is it worth doing this as the ComputationalTool release is in progress?
> 
> The profile needs to go out for community comment, and this would be something that I would provide as a comment, so yes it is worth getting fixed.

I agree with @AlasdairGray (input, output, maintainer) we want the profile and examples as complete and accurate as possible so adopters will not have to change things too soon.

**Review by AlasdairGray — APPROVED** [review]
Thanks for the changes @albangaignard 

I've captured the input/output as a separate issue

**Pull request merged**
